# Generated by Django 5.0 on 2023-12-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrmodel',
            name='pdf_file',
            field=models.FileField(upload_to='tmp/pdf/'),
        ),
    ]
